language: go

# Use latest go version
go:
  - 1.x
os:
  - linux
  - osx
  - windows

before_deploy:
  - go get github.com/karalabe/xgo
  - docker build --tag xgo-builder xgo
  - xgo -image xgo-builder --targets=windows/amd64,darwin/amd64,linux/amd64 .
  - ls

deploy:
  provider: releases
  api_key:
    secure: +/2ebfs+adJi/UUzNBO6//JuZKeMEgUuTLM+7agXCg9bJzthVHFxcQyFfP/evkm9+OWLpJrKAQc9LieYxgySesZRxzlqLj9zU9WBdoAE46YlOQUvTYuN6pUAD4bhNoR+enLVvYZVn6jSuRF/ggvUqE7kw537GpnaA9qGepGBuvYdFcuIo/EUddc3i24e9FYhgOWxjaBf7SR/G/G/b7jCqCows6SSOtalZP06fcgk/yXG4x654crjxAphgOd9aKHHs8xKRc6YiuJmqw5XVWLePXkXgrum7vzmuEMaLD8ubrPv9OZ9DI8qyXnWhONSPdaYzF8bRKGQLA1/6OvaK7CPH8/a/gL/IzgJwHLngiHJ/sBwrweX+gp7dKW9SeYzS9ojphYwMDlNMju5i2fGZQO862tBx0=
  file:
    - pegnetd-darwin-10.6-amd64
    - pegnetd-linux-amd64
    - pegnetd-windows.exe
  skip_cleanup: true
  on:
     tags: true
